import React from 'react';
import { Meta, Story } from '@storybook/react';
import { Button } from '../src';

const meta: Meta = {
  title: 'Button',
  component: Button,
  argTypes: {
    children: {
      control: {
        type: 'text',
      },
    },
  },
  parameters: {
    controls: { expanded: true },
  },
};

export default meta;

// By passing using the Args format for exported stories, you can control the props for a component for reuse in a test
// https://storybook.js.org/docs/react/workflows/unit-testing

// This might be useful for testing???

// TODO: Discuss this poin
// Opinion it might be better to use .tsx because of the following
// 1. I can reuse the components in my unit tests
// 2. The autogenerated docs are pretty sweet. MDX would be more fun, but it would be harder to maintain.
const Template: Story = (args) => <Button {...args} />;

const Default: Story = (args) => <Button text="Default Button" {...args} />;

const Primary: Story = (args) => (
  <Button text="Primary Button" type="Primary" {...args} />
);

const Secondary: Story = (args) => (
  <Button text="Secondary Button" type="Secondary" {...args} />
);

export { Default, Primary, Secondary };
